version: 2
jobs:
  cypress/run:
    docker:
      - image: cypress/base:10
    working_directory: ~/app   
    parallelism: 1
    steps:
    - checkout
    - restore_cache:
       keys:
       - cache-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Install dependencies
        command: npm ci
    - run:
        command: npx cypress verify
    - save_cache:
        key: cache-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/.npm
        - ~/.cache
    - run:
        name: Running E2E tests with JUnit reporter
        command: npm run test-junit
    - store_test_results:
       path: /junit-results
    - store_artifacts:
       path: app/cypress/videos
    - store_artifacts:
       path: app/cypress/screenshots
workflows:
  build:
    jobs:
    - cypress/run
  version: 2
